#!/bin/env python

import os
import re
import subprocess
import sys

if len(sys.argv) > 1:
    exe = os.path.realpath(sys.argv[1])
else:
    exe = './dynamic-debug'

testsDir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'tests')

runCount = 0
passCount = 0

def runTest(dirname, name):
    global runCount, passCount
    runCount += 1
    filename = os.path.join(dirname, name)

    with open(filename) as f:
        line = f.readline().rstrip()
    match = re.match('# (\w+): (.*)$', line)
    if not match:
        return 'BAD'
    if match.group(1) != 'output':
        return 'BAD'
    expect = match.group(2)

    try:
        ok = True
        output = subprocess.check_output([exe, filename], stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        ok = False
        output = e.output

    if not ok:
        return 'FAIL'
    if output.rstrip() != expect:
        print(expect)
        print(output)
        return 'FAIL'

    passCount += 1
    return 'PASS'

def runTestDir(arg, dirname, names):
    print(dirname)
    for name in names:
        if name.endswith('.py'):
            result = runTest(dirname, name)
            print('  %-20s %s' % (name, result))

print("Running tests...")
os.path.walk(testsDir, runTestDir, None)
print("%d tests passed out of %d" % (passCount, runCount))
if passCount != runCount:
    sys.exit(1)
